
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#a ok
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
  
weather:
  - platform: environment_canada
    station: "QC/s0000635"

google_assistant:
  project_id: !secret id_gassistant
  service_account: !secret saccount_json
  report_state: true
  expose_by_default: true

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 30
    consider_home: 360
    new_device_defaults:
      track_new_devices: False
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    interval_seconds: 30
    consider_home: 360
    new_device_defaults:
      track_new_devices: true
    exclude:
     - 192.168.1.30
     - 192.168.1.31
     - 192.168.1.70
     - 192.168.1.1
     - 192.168.1.6
     - 192.168.1.7
     - 192.168.1.8
     - 192.168.1.15
     - 192.168.1.60
     - 192.168.1.61
     - 192.168.1.62
     - 192.168.1.3
     - 192.168.1.2

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
person: !include persons.yaml

recorder:
  purge_keep_days: 93
  purge_interval: 1
  db_url: sqlite:///mnt/storage/database/recorder
  exclude:
    domains:
      - automation
      - Updater

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  server_port: 8123
  ssl_profile: modern

sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret cert_expiry
  - platform: environment_canada
    station: "QC/s0000635"

mqtt:
  broker: 127.0.0.1
  port: 1883
  username: hass
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret conf_url

#device_tracker:
#  - platform: google_maps
#    username: !secret google_maps_email
#    password: !secret google_maps_pass
#    debug: false
#    max_gps_accuracy: 100
